# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirmationDialog(object):
   def setupUi(self, Dialog):
       Dialog.setObjectName("Dialog")
       self.label = QtWidgets.QLabel(Dialog)
       self.label.setGeometry(QtCore.QRect(30, 10, 181, 41))
       self.label.setObjectName("label")
       self.label_2 = QtWidgets.QLabel(Dialog)
       self.label_2.setGeometry(QtCore.QRect(90, 40, 41, 31))
       self.label_2.setObjectName("label_2")
       self.pushButton = QtWidgets.QPushButton(Dialog)
       self.pushButton.setGeometry(QtCore.QRect(70, 70, 81, 32))
       self.pushButton.setObjectName("pushButton")


       self.retranslateUi(Dialog)
       self.pushButton.clicked.connect(Dialog.accept) # type: ignore
       QtCore.QMetaObject.connectSlotsByName(Dialog)


   def retranslateUi(self, Dialog):
       _translate = QtCore.QCoreApplication.translate
       Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
       self.label.setText(_translate("Dialog", "Successfully"))
       self.label_2.setText(_translate("Dialog", "saved!"))
       self.pushButton.setText(_translate("Dialog", "Ok"))


if __name__ == "__main__":
   import sys
   app = QtWidgets.QApplication(sys.argv)
   Dialog = QtWidgets.QDialog()
   ui = Ui_confirmationDialog()
   ui.setupUi(Dialog)
   Dialog.show()
   sys.exit(app.exec_())
